# Boolean Mask Review

A boolean mask is an array of ```True``` and ```False``` values. Boolean masks are created with logical statements (statements that return ```True``` and ```False```). Boolean masks can be used to index arrays and pull out values that correspond to a range of interest.

In [2]:
import numpy as np

data = np.arange(0,11)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# index out the numbers 3 and lower and index out the numbers 7 and higher

mask1 = data<=3
mask1

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [5]:
mask2 = data>=7
mask2

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [6]:
mask = np.logical_or(mask1,mask2)
mask

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True,  True])

In [8]:
nums_i_want = data[mask]
nums_i_want

array([ 0,  1,  2,  3,  7,  8,  9, 10])