## Indexing Lists and Strings

In [1]:
lst = ['w','x','y','z']

In [2]:
# index out x,y,z
lst[1:4]

['x', 'y', 'z']

In [3]:
lst[1:]

['x', 'y', 'z']

In [4]:
lst[0:2]

['w', 'x']

In [5]:
lst[:2]

['w', 'x']

In [6]:
lst

['w', 'x', 'y', 'z']

In [7]:
lst[0:3:2]

['w', 'y']

In [8]:
lst[::2]

['w', 'y']

In [9]:
lst[1:4:2]

['x', 'z']

In [10]:
lst[1::2]

['x', 'z']

In [11]:
lst[1:2]

['x']

In [12]:
s = 'Engineering'

In [13]:
s[0:3]

'Eng'

In [14]:
s[:3]

'Eng'

In [20]:
s[8:11]

'ing'

In [21]:
s[8:]

'ing'

In [22]:
s

'Engineering'

In [31]:
s[-3::1]

'ing'

In [33]:
s[:6]

'Engine'

In [35]:
s[3:5:1]

'in'

In [37]:
s[7::]

'ring'

In [38]:
s[2:5]

'gin'

In [1]:
s ='programming today'

In [9]:
s=[['wow'],'programming today']

In [12]:
s[0][0][:3]

'wow'

## Indexing NumPy arrays

In [14]:
import numpy as np

In [15]:
a = np.array([10,20,30,40,50])   #module.function

In [16]:
a

array([10, 20, 30, 40, 50])

In [17]:
a[1:4:2]

array([20, 40])

In [18]:
a[::-1]

array([50, 40, 30, 20, 10])

In [19]:
a[0:5:2]

array([10, 30, 50])

In [20]:
a[::2]

array([10, 30, 50])

In [21]:
b = np.array([10,20,30,40,50,60])

In [22]:
b

array([10, 20, 30, 40, 50, 60])

In [26]:
b.reshape(2,3) # 2 row, 3 columns

array([[10, 20, 30],
       [40, 50, 60]])

In [27]:
b

array([10, 20, 30, 40, 50, 60])

In [28]:
c = b.reshape(2,3)

In [29]:
c

array([[10, 20, 30],
       [40, 50, 60]])

In [30]:
c[0]

array([10, 20, 30])

In [31]:
c[1]

array([40, 50, 60])

In [32]:
c[0][1]    #[row][col]

20

In [33]:
c[1][2]

60

In [38]:
c[:][0:3]

array([[10, 20, 30],
       [40, 50, 60]])

In [39]:
c

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
c[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [59]:
c[0:2,1:3] # need to include comma. [row,col]

array([[20, 30],
       [50, 60]])

In [62]:
c[1,2]

60

In [68]:
a = np.array([1,2,3])
b = np.array([2,4,6])

In [69]:
a*b

array([ 2,  8, 18])

In [70]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is 44E5-0D98

 Directory of C:\Users\student\Desktop

01/15/2019  03:08 PM    <DIR>          .
01/15/2019  03:08 PM    <DIR>          ..
01/15/2019  03:04 PM    <DIR>          .ipynb_checkpoints
05/13/2016  12:33 PM               210 MSDS Online.url
06/10/2015  01:29 PM    <DIR>          Safety Information
01/15/2019  03:06 PM               922 Untitled.ipynb
01/15/2019  03:06 PM             1,024 Untitled1.ipynb
01/15/2019  03:07 PM            10,204 weather_data.xlsx
01/15/2019  03:05 PM            14,830 week2.ipynb
               5 File(s)         27,190 bytes
               4 Dir(s)  299,312,857,088 bytes free


In [76]:
import pandas as pd

In [81]:
df = pd.read_excel('weather_data.xlsx', header=None)

In [85]:
df.tail()

0    1   2   3    4   5   6   7   8    9   ...    21  22   23  24   25  \
7    0   45   0   0    0   0   0   0   5    0  ...     0   0  158  62    1   
8    0    0   0   0    0   0   0   0   0    0  ...    37   0    0   0    0   
9    0    0   0  14  156   0   0   0   0  110  ...     0   0    0   0    0   
10   1  163   5   0    0   0   0   0   0    0  ...     0   2    2  10  255   
11   0    0   0   0    0  45   0   0   0   15  ...    34   0    0   0    0   

    26   27  28  29     30  
7    0    0   0   0      0  
8    6  138  58  10 -99999  
9    0    0   0   0      1  
10   2    0   0   0 -99999  
11   0    0   0   0      0  

[5 rows x 31 columns]

In [86]:
d = np.array(df)

In [88]:
type(d)

numpy.ndarray

In [89]:
import pandas as pd

In [91]:
df = pd.read_excel('weather_data.xlsx', header=None)

In [93]:
d = np.array(df)

In [94]:
type(d)

numpy.ndarray

In [95]:
d[0,14]

85

In [98]:
d[0,8]

26

In [99]:
d_in=d*0.01

In [100]:
d_in

array([[ 0.0000e+00,  0.0000e+00,  2.7200e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  9.0000e-02,  2.6000e-01,  1.0000e-02,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  5.0000e-01,  8.5000e-01,
         0.0000e+00,  0.0000e+00,  9.0000e-01,  9.0000e-02,  0.0000e+00,
         0.0000e+00,  1.0000e-02,  1.5000e-01,  2.2400e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  3.3000e-01,
         3.3000e-01],
       [ 6.1000e-01,  1.0300e+00,  0.0000e+00,  2.0000e-02,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  2.0000e-02,  0.0000e+00,  6.8000e-01,
         3.0000e-02,  3.0000e-02,  1.0000e-02,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  1.0000e-02,  1.3500e+00,  3.0000e-02,  6.6000e-01,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  5.0000e-02,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  6.2000e-01, -9.9999e+02, -9.9999e+02,
        -9.9999e+02],
       [ 2.0000e-02,  0.0000e+00,  1.7000e-01,  2.7000e-01,  0.0000e+00,
       