# Week 3 Notes

## Quick review of dictionaries

In [1]:
# list contains individual elements
l = ['ENGR','CMET']
l[0]

'ENGR'

In [2]:
# dictionary contains key:value pairs
d = {'ENGR':4,'CMET':3}
d['ENGR']

4

In [4]:
d.keys()

dict_keys(['ENGR', 'CMET'])

In [5]:
d.values()

dict_values([4, 3])

In [6]:
d.pop('CMET')
d

{'ENGR': 4}

In [7]:
d.pop('ENGR')
d

{}

In [10]:
del d['ENGR']

SyntaxError: invalid syntax (<ipython-input-10-224c2cfb9324>, line 1)

In [11]:
d = {'ENGR':40}
d

{'ENGR': 40}

In [12]:
del d['ENGR']
d

{}

In [14]:
d = {2:['ENGR','CMET']}
d

{2: ['ENGR', 'CMET']}

In [15]:
d[2]

['ENGR', 'CMET']

In [18]:
s = {'ENGR','*NGR'}
s

{'*NGR', 'ENGR'}

In [20]:
d = {'ENGR':4,'CMET':4}
d

{'ENGR': 4, 'CMET': 4}

In [21]:
d.values()==4

False

## Quick review of NumPy indexing and slicing

In [22]:
import numpy as np

In [28]:
b = np.arange(1,10+1,1) #start,stop,step    REMEMBER TO STOP at STOP+STEP AS STOP VALUE IS NOT INCLUDED
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
b = b.reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
# get 2,7 out
b[0:2,1]

array([2, 7])

In [31]:
b[:,1]

array([2, 7])

In [34]:
# get 8,9 out
b[1,2:4]

array([8, 9])

In [35]:
# get 1,3,5
b[0,0:5:2]   # b[row,col] more specifically b[row,col_start:col_end:col_step]

array([1, 3, 5])

In [36]:
# get 7,9
b[1,1:4:2]

array([7, 9])

In [37]:
# get 2,7 and 4,9
b[:,1:4:2]   #b[all_rows, start_col 1: end_col 4: step_cols by 2]

array([[2, 4],
       [7, 9]])

In [38]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
mask = b<3.5  # make a boolean mask
mask

array([[ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [41]:
#get out values less than 3.5
b[mask]

array([1, 2, 3])

In [42]:
#get out values greater than 7.5
mask = b>7.5
mask

array([[False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [43]:
b[mask]

array([ 8,  9, 10])

In [44]:
# get out values less than 5
b[b<5.5]

array([1, 2, 3, 4, 5])

In [45]:
# Boolean values can be compared with ```and```, ```or```, ```not```.

a = True
b = False
c = a and b
c

False

In [50]:
b = np.arange(1,10+1,1).reshape(2,5)
b



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
mask1 = b<3.5
mask1

array([[ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [52]:
mask2 = b>7.5
mask2

array([[False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [53]:
# values less than 4 and greater than 7
mask = np.logical_or(mask1,mask2)     # boolean arrays must be compared with np.logical_or(), np.logical_and()
mask

array([[ True,  True,  True, False, False],
       [False, False,  True,  True,  True]])

In [54]:
b[mask]

array([ 1,  2,  3,  8,  9, 10])

In [55]:
# values 3 and greater but less than 7 (3,4,5,6)

In [56]:
mask1 = b>=3
mask1

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
mask2 = b<7
mask2

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False]])

In [58]:
mask = np.logical_and(mask1,mask2)
mask

array([[False, False,  True,  True,  True],
       [ True, False, False, False, False]])

In [59]:
b[mask]

array([3, 4, 5, 6])

## NumPy's np.meshgrid() function

In [63]:
# create a 2D array
x = np.array([[1, 2, 3, 4, 5],[2, 10, 15, 20, 25]])
x

array([[ 1,  2,  3,  4,  5],
       [ 2, 10, 15, 20, 25]])

In [65]:
x = np.array([1,2,3])
y = np.array([10,20,30,40,50])
X, Y = np.meshgrid(x,y)
X

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [66]:
Y

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40],
       [50, 50, 50]])

In [67]:
X*Y

array([[ 10,  20,  30],
       [ 20,  40,  60],
       [ 30,  60,  90],
       [ 40,  80, 120],
       [ 50, 100, 150]])

## create a 10 by 10 multiplication table

In [69]:
x = np.arange(1,10+1,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
y = np.arange(1,11,1)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
X, Y = np.meshgrid(x,y)
X

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [72]:
Y

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [73]:
m_table = X * Y
m_table

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [74]:
# calculate 8 x 6
m_table[8,6]

63

In [75]:
col = np.where(m_table[0,:]==8)
col

(array([7], dtype=int64),)

In [76]:
row = np.where(m_table[:,0]==6)
row

(array([5], dtype=int64),)

In [80]:
m_table[row,col]

array([[48]])

In [81]:
m_table[row[0],col[0]][0]

48